In [2]:
import pandas as pd

In [3]:
matches = pd.read_csv("https://raw.githubusercontent.com/evanc108/nba-betting-predictor/main/NBA%20Game%20Data/games.csv", header=0)

In [4]:
matches.head()

,GAME_DATE_EST,GAME_ID,GAME_STATUS_TEXT,HOME_TEAM_ID,VISITOR_TEAM_ID,SEASON,TEAM_ID_home,PTS_home,FG_PCT_home,FT_PCT_home,...,AST_home,REB_home,TEAM_ID_away,PTS_away,FG_PCT_away,FT_PCT_away,FG3_PCT_away,AST_away,REB_away,HOME_TEAM_WINS
0,2022-12-22,22200477,Final,1610612740,1610612759,2022,1610612740,126.0,0.484,0.926,...,25.0,46.0,1610612759,117.0,0.478,0.815,0.321,23.0,44.0,1
1,2022-12-22,22200478,Final,1610612762,1610612764,2022,1610612762,120.0,0.488,0.952,...,16.0,40.0,1610612764,112.0,0.561,0.765,0.333,20.0,37.0,1
2,2022-12-21,22200466,Final,1610612739,1610612749,2022,1610612739,114.0,0.482,0.786,...,22.0,37.0,1610612749,106.0,0.470,0.682,0.433,20.0,46.0,1
3,2022-12-21,22200467,Final,1610612755,1610612765,2022,1610612755,113.0,0.441,0.909,...,27.0,49.0,1610612765,93.0,0.392,0.735,0.261,15.0,46.0,1
4,2022-12-21,22200468,Final,1610612737,1610612741,2022,1610612737,108.0,0.429,1.000,...,22.0,47.0,1610612741,110.0,0.500,0.773,0.292,20.0,47.0,0

In [5]:
new_data = pd.DataFrame(columns=[
    'Date', 'Game_ID', 'Game_Status',
    'Team', 'Opponent', 'Location',
    'Season', 'PTS', 'FG_PCT', 'FT_PCT', 'FG3_PCT', 'AST', 'REB',
    'Outcome'
])

In [6]:
for index, row in matches.iterrows():
    home_team_data = [
        row['GAME_DATE_EST'], row['GAME_ID'], row['GAME_STATUS_TEXT'],
        row['HOME_TEAM_ID'], row['VISITOR_TEAM_ID'],
        'Home', row['SEASON'], row['PTS_home'], row['FG_PCT_home'], row['FT_PCT_home'],
        row['FG3_PCT_home'], row['AST_home'], row['REB_home'],
        'Won' if row['HOME_TEAM_WINS'] == 1 else 'Lost'  # Winner determination
    ]
    
    away_team_data = [
        row['GAME_DATE_EST'], row['GAME_ID'], row['GAME_STATUS_TEXT'],
        row['VISITOR_TEAM_ID'], row['HOME_TEAM_ID'],
        'Away', row['SEASON'], row['PTS_away'], row['FG_PCT_away'], row['FT_PCT_away'],
        row['FG3_PCT_away'], row['AST_away'], row['REB_away'],
        'Lost' if row['HOME_TEAM_WINS'] == 1 else 'Won'  # Winner determination
    ]
    
    home_team_df = pd.DataFrame([home_team_data], columns=new_data.columns)
    away_team_df = pd.DataFrame([away_team_data], columns=new_data.columns)
    
    new_data = pd.concat([new_data, home_team_df, away_team_df], ignore_index=True)

new_data.to_csv('reorganized_data.csv', index=False)

In [7]:
new_data.head(20)

,Date,Game_ID,Game_Status,Team,Opponent,Location,Season,PTS,FG_PCT,FT_PCT,FG3_PCT,AST,REB,Outcome
0,2022-12-22,22200477,Final,1610612740,1610612759,Home,2022,126.0,0.484,0.926,0.382,25.0,46.0,Won
1,2022-12-22,22200477,Final,1610612759,1610612740,Away,2022,117.0,0.478,0.815,0.321,23.0,44.0,Lost
2,2022-12-22,22200478,Final,1610612762,1610612764,Home,2022,120.0,0.488,0.952,0.457,16.0,40.0,Won
3,2022-12-22,22200478,Final,1610612764,1610612762,Away,2022,112.0,0.561,0.765,0.333,20.0,37.0,Lost
4,2022-12-21,22200466,Final,1610612739,1610612749,Home,2022,114.0,0.482,0.786,0.313,22.0,37.0,Won
5,2022-12-21,22200466,Final,1610612749,1610612739,Away,2022,106.0,0.470,0.682,0.433,20.0,46.0,Lost
6,2022-12-21,22200467,Final,1610612755,1610612765,Home,2022,113.0,0.441,0.909,0.297,27.0,49.0,Won
7,2022-12-21,22200467,Final,1610612765,1610612755,Away,2022,93.0,0.392,0.735,0.261,15.0,46.0,Lost
8,2022-12-21,22200468,Final,1610612737,1610612741,Home,2022,108.0,0.429,1.000,0.378,22.0,47.0,Lost
9,2022-12-21,22200468,Final,1610612741,1610612737,Away,2022,110.0,0.500,0.773,0.292,20.0,47.0,Won
10,2022-12-21,22200469,Final,1610612738,1610612754,Home,2022,112.0,0.386,0.840,0.317,26.0,62.0,Lost
11,2022-12-21,22200469,Final,1610612754,1610612738,Away,2022,117.0,0.469,0.778,0.462,27.0,47.0,Won
12,2022-12-21,22200470,Final,1610612751,1610612744,Home,2022,143.0,0.643,0.875,0.636,42.0,32.0,Won
13,2022-12-21,22200470,Final,1610612744,1610612751,Away,2022,113.0,0.494,0.760,0.364,32.0,36.0,Lost
14,2022-12-21,22200471,Final,1610612752,1610612761,Home,2022,106.0,0.553,0.611,0.423,25.0,38.0,Lost
15,2022-12-21,22200471,Final,1610612761,1610612752,Away,2022,113.0,0.447,0.909,0.265,17.0,38.0,Won
16,2022-12-21,22200472,Final,1610612745,1610612753,Home,2022,110.0,0.466,0.647,0.395,22.0,49.0,Lost
17,2022-12-21,22200472,Final,1610612753,1610612745,Away,2022,116.0,0.451,0.697,0.297,19.0,45.0,Won
18,2022-12-21,22200473,Final,1610612750,1610612742,Home,2022,99.0,0.494,0.700,0.267,23.0,39.0,Lost
19,2022-12-21,22200473,Final,1610612742,1610612750,Away,2022,104.0,0.453,0.852,0.333,17.0,39.0,Won

In [8]:
nba_df = new_data;

In [9]:
nba_df.head()

,Date,Game_ID,Game_Status,Team,Opponent,Location,Season,PTS,FG_PCT,FT_PCT,FG3_PCT,AST,REB,Outcome
0,2022-12-22,22200477,Final,1610612740,1610612759,Home,2022,126.0,0.484,0.926,0.382,25.0,46.0,Won
1,2022-12-22,22200477,Final,1610612759,1610612740,Away,2022,117.0,0.478,0.815,0.321,23.0,44.0,Lost
2,2022-12-22,22200478,Final,1610612762,1610612764,Home,2022,120.0,0.488,0.952,0.457,16.0,40.0,Won
3,2022-12-22,22200478,Final,1610612764,1610612762,Away,2022,112.0,0.561,0.765,0.333,20.0,37.0,Lost
4,2022-12-21,22200466,Final,1610612739,1610612749,Home,2022,114.0,0.482,0.786,0.313,22.0,37.0,Won

In [10]:
nba_df["Target"] = (nba_df["Outcome"] == "Won").astype("int")

In [12]:
1 + 3 + 5

9